# Generated by Django 2.2 on 2023-02-10 22:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(max_length=50)),
                ('ano', models.CharField(blank=True, max_length=1, null=True)),
                ('comision', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('titulo_libro', models.CharField(max_length=100)),
                ('editor', models.CharField(default='', max_length=200, null=True)),
                ('año_publicacion', models.CharField(max_length=5)),
                ('nombre_capitulo', models.CharField(default='', max_length=50, null=True)),
                ('ubicacion', models.CharField(default='', max_length=50, null=True)),
                ('es_obligatorio', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_carrera', models.CharField(max_length=50)),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='carrera', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_competencia', models.CharField(choices=[('T', 'Tecnológicas'), ('E', 'Específicas'), ('S', 'Sociales, políticas y actitudinales')], max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatosDescriptivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.CharField(blank=True, max_length=50, null=True)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('area_bloque', models.CharField(blank=True, max_length=50, null=True)),
                ('porcentaje_horas_en_carrera', models.CharField(blank=True, max_length=50, null=True)),
                ('porcentaje_horas_en_area', models.CharField(blank=True, max_length=50, null=True)),
                ('nivel', models.CharField(blank=True, max_length=50, null=True)),
                ('ciclo_lectivo', models.IntegerField(blank=True, null=True)),
                ('carga_horaria_total', models.FloatField(blank=True, max_length=50, null=True)),
                ('carga_horaria_semanal', models.FloatField(blank=True, max_length=50, null=True)),
                ('cursado', models.CharField(blank=True, choices=[('A', 'Anual'), ('1', '1er Cuatrimestre'), ('2', '2do Cuatrimestre')], default='A', max_length=1, null=True)),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Asignatura')),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Dedicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dedicacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DiasCursado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstrategiasEns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=3)),
                ('estrategia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FechaCalendarioAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('nombre_mes', models.CharField(max_length=100, null=True)),
                ('nombre_dia', models.CharField(max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('ciclo_lectivo', models.IntegerField(null=True)),
                ('hay_clase', models.BooleanField(null=True)),
                ('editable', models.BooleanField(null=True)),
                ('actividad', models.CharField(blank=True, choices=[('IC1', 'Inicio de clases 1er cuatrimestre'), ('FC1', 'Fin de clases 1er cuatrimestre'), ('IC2', 'Inicio de clases 2do cuatrimestre'), ('FC2', 'Fin de clases 2do cuatrimestre'), ('EF', 'Examen final con suspensión de clase'), ('EF', 'Examen final sin suspensión de clase'), ('RI', 'Receso de invierno'), ('F', 'Feriado'), ('DN', 'Dia Normal')], max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fundamentacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fundamentos', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('P', 'En proceso'), ('A', 'Aprobada'), ('R', 'En revision'), ('C', 'A corregir')], max_length=2)),
                ('fecha_creacion', models.DateTimeField(auto_now=True, max_length=50)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('eliminada', models.BooleanField(default=False, null=True)),
                ('condicion_aprobacion_directa', models.CharField(blank=True, max_length=3000, null=True)),
                ('condicion_aprobacion_cursada', models.CharField(blank=True, max_length=3000, null=True)),
                ('justificacion_ordenanza', models.CharField(blank=True, max_length=3000, null=True)),
                ('numero_comisiones', models.IntegerField(blank=True, default=1, null=True)),
                ('numero_estudiantes_comision', models.IntegerField(blank=True, null=True)),
                ('sincronizado_calendario_academico', models.BooleanField(default=False, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Asignatura')),
                ('datos_descriptivos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.DatosDescriptivos')),
                ('fundamentacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Fundamentacion')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoDeAprendizaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.CharField(max_length=300)),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Asignatura')),
                ('planificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Situacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('situacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('D', 'Diagnóstica'), ('F', 'Formativa'), ('S', 'Sumativa'), ('SF', 'Sumativa Final')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Webgrafia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('titulo_publicacion', models.CharField(max_length=100)),
                ('nombre_pagina', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('link_pagina', models.CharField(max_length=100)),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('planificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('planificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion')),
            ],
        ),
        migrations.CreateModel(
            name='TareasFunciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tarea_funcion', models.CharField(max_length=50)),
                ('planificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion')),
            ],
        ),
        migrations.CreateModel(
            name='SubCompetencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Competencia')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoDeAprendizajeAnterior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Asignatura')),
                ('planificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion')),
                ('resultado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.ResultadoDeAprendizaje')),
            ],
        ),
        migrations.CreateModel(
            name='PropuestaDesarrollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_dentro_aula', models.CharField(blank=True, max_length=3000, null=True)),
                ('actividad_fuera_aula', models.CharField(blank=True, max_length=3000, null=True)),
                ('tiempo_dentro_aula', models.CharField(blank=True, max_length=50, null=True)),
                ('tiempo_fuera_aula', models.CharField(blank=True, max_length=50, null=True)),
                ('modo_agrupamiento', models.CharField(blank=True, max_length=500, null=True)),
                ('materiales_equipamiento', models.CharField(blank=True, max_length=500, null=True)),
                ('bibliografias', models.ManyToManyField(blank=True, null=True, to='planificaciones.Bibliografia')),
                ('estrategias_ens', models.ManyToManyField(blank=True, null=True, to='planificaciones.EstrategiasEns')),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion')),
                ('resultados_de_aprendizaje', models.ManyToManyField(blank=True, null=True, to='planificaciones.ResultadoDeAprendizaje')),
                ('subcompetencias', models.ManyToManyField(blank=True, null=True, to='planificaciones.SubCompetencia')),
                ('unidades', models.ManyToManyField(blank=True, null=True, to='planificaciones.Unidad')),
            ],
        ),
        migrations.CreateModel(
            name='PlanificacionUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleProfesorCatedra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actividades', models.CharField(blank=True, max_length=3000, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Categoria')),
                ('dedicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Dedicacion')),
                ('planificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('situacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Situacion')),
                ('tareas', models.ManyToManyField(blank=True, to='planificaciones.TareasFunciones')),
            ],
        ),
        migrations.AddField(
            model_name='datosdescriptivos',
            name='dias',
            field=models.ManyToManyField(blank=True, to='planificaciones.DiasCursado'),
        ),
        migrations.CreateModel(
            name='Correccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correccion', models.CharField(max_length=300)),
                ('seccion', models.IntegerField(blank=True, default=1, null=True)),
                ('estado', models.CharField(blank=True, choices=[('G', 'Generado'), ('R', 'Resuelto')], max_length=15, null=True)),
                ('planificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion')),
            ],
            options={
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivos', models.CharField(max_length=3000)),
                ('contenido', models.CharField(max_length=3000)),
                ('carga_horaria', models.CharField(max_length=100)),
                ('planificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion')),
                ('unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Unidad')),
            ],
        ),
        migrations.AddField(
            model_name='competencia',
            name='planificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=500)),
                ('correccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='planificaciones.Correccion')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_desarrollo_de_clase', models.CharField(blank=True, max_length=400, null=True)),
                ('fecha_clase', models.DateField(blank=True, default=datetime.date(2023, 2, 10), null=True)),
                ('es_examen', models.CharField(blank=True, choices=[('P', 'Examen parcial'), ('R', 'Examen recuperatorio'), ('F', 'Examen final'), ('NA', 'No aplica')], max_length=50, null=True)),
                ('numero_de_clase_o_semana', models.IntegerField(blank=True, default=0, null=True)),
                ('cantidad_tareas', models.IntegerField(blank=True, default=0, null=True)),
                ('planificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion')),
                ('profesor_a_cargo', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
                ('resultado_de_aprendizaje', models.ManyToManyField(blank=True, null=True, to='planificaciones.ResultadoDeAprendizaje')),
                ('unidad_tematica_o_tema', models.ManyToManyField(blank=True, null=True, to='planificaciones.Contenido')),
            ],
        ),
        migrations.AddField(
            model_name='bibliografia',
            name='planificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Carrera'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='profesor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(choices=[('A', 'Autoevaluación'), ('C', 'Coevaluación'), ('H', 'Heteroevaluación')], max_length=2)),
                ('lugar', models.CharField(max_length=20)),
                ('indicadores_de_logro', models.CharField(max_length=100)),
                ('tecnicas_de_evaluacion', models.CharField(max_length=100)),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion')),
                ('resultados_de_aprendizaje', models.ManyToManyField(null=True, to='planificaciones.ResultadoDeAprendizaje')),
                ('tipo_de_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.TipoDeEvaluacion')),
                ('unidad_tematica', models.ManyToManyField(to='planificaciones.Unidad')),
            ],
        ),
    ]
