# Generated by Django 2.2 on 2021-09-02 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='situacion',
        ),
    ]
