# Generated by Django 2.2 on 2023-02-25 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(blank=True, default=datetime.date(2023, 2, 25), null=True),
        ),
        migrations.AlterField(
            model_name='datosdescriptivos',
            name='dias',
            field=models.ManyToManyField(blank=True, null=True, to='planificaciones.DiasCursado'),
        ),
    ]
