# Generated by Django 2.2 on 2021-08-17 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0002_auto_20210816_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.DateTimeField(max_length=50)),
                ('departamento', models.DateTimeField(max_length=50)),
                ('areaBloque', models.DateTimeField(max_length=50)),
                ('porcentajeHorasenCarrera', models.DateTimeField(max_length=50)),
                ('porcentajeHorasenArea', models.DateTimeField(max_length=50)),
                ('nivel', models.DateTimeField(max_length=50)),
                ('cicloLectivo', models.DateTimeField(max_length=50)),
                ('cargaHorariaTotal', models.DateTimeField(max_length=50)),
                ('cargaHorariaSemanal', models.DateTimeField(max_length=50)),
                ('cursado', models.DateTimeField(max_length=50)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Asignatura')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateTimeField(max_length=50)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Asignatura')),
                ('seccion1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Seccion1')),
            ],
        ),
    ]
