# Generated by Django 2.2 on 2021-09-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0002_remove_profesor_situacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacion',
            name='eliminar',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
