# Generated by Django 3.2.6 on 2021-09-17 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0002_remove_profesor_situacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoDeAprendizaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('D', 'Diagnóstica'), ('F', 'Formativa'), ('S', 'Sumativa'), ('SF', 'Sumativa Final')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(choices=[('A', 'Autoevaluación'), ('C', 'Coevaluación'), ('H', 'Heteroevaluación')], max_length=2)),
                ('unidad_tematica', models.CharField(max_length=30)),
                ('lugar', models.CharField(max_length=20)),
                ('indicadores_de_logro', models.CharField(max_length=100)),
                ('tecnicas_de_evaluacion', models.CharField(max_length=100)),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.planificacion')),
                ('resultados_de_aprendizaje', models.ManyToManyField(null=True, to='planificaciones.ResultadoDeAprendizaje')),
                ('tipo_de_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.tipodeevaluacion')),
            ],
        ),
    ]
