# Generated by Django 2.2 on 2021-08-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0003_planificacion_seccion1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion1',
            name='areaBloque',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seccion1',
            name='cargaHorariaSemanal',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seccion1',
            name='cargaHorariaTotal',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seccion1',
            name='cicloLectivo',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seccion1',
            name='departamento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seccion1',
            name='institucion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seccion1',
            name='nivel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seccion1',
            name='porcentajeHorasenArea',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seccion1',
            name='porcentajeHorasenCarrera',
            field=models.CharField(max_length=50),
        ),
    ]
