# Generated by Django 2.2 on 2021-09-07 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0003_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='contenido',
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_contenido', models.CharField(max_length=50)),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Unidad')),
            ],
        ),
    ]
