# Generated by Django 2.2 on 2021-08-18 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0004_auto_20210817_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='seccion1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Seccion1'),
        ),
    ]
