# Generated by Django 2.2 on 2021-09-07 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0004_auto_20210907_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='planificiacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion'),
        ),
    ]
