# Generated by Django 2.2 on 2021-09-07 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0005_unidad_planificiacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidad',
            old_name='planificiacion',
            new_name='planificacion',
        ),
    ]
