# Generated by Django 3.2.6 on 2021-08-27 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0006_auto_20210818_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(choices=[('A', 'Autoevaluación'), ('C', 'Coevaluación'), ('H', 'Heteroevaluación')], max_length=2)),
                ('unidad_tematica', models.CharField(max_length=30)),
                ('lugar', models.CharField(max_length=20)),
                ('indicadores_de_logro', models.CharField(max_length=100)),
                ('tecnicas_de_evaluacion', models.CharField(max_length=100)),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.planificacion')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('D', 'Diagnóstica'), ('F', 'Formativa'), ('S', 'Sumativa'), ('SF', 'Sumativa Final')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoDeAprendizaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('actividad', models.ManyToManyField(to='planificaciones.Actividad')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo_de_evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.tipodeevaluacion'),
        ),
    ]
