# Generated by Django 2.2 on 2021-09-21 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0007_auto_20210920_2055'),
        ('planificaciones', '0004_competencia_planificacion'),
    ]

    operations = [
    ]
