# Generated by Django 3.2.6 on 2021-09-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0007_auto_20210827_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadodeaprendizaje',
            name='actividad',
        ),
        migrations.AddField(
            model_name='actividad',
            name='resultados_de_aprendizaje',
            field=models.ManyToManyField(to='planificaciones.ResultadoDeAprendizaje'),
        ),
    ]
