# Generated by Django 2.2 on 2023-03-11 20:15

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0007_auto_20230307_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='profesor',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(blank=True, default=datetime.date(2023, 3, 11), null=True),
        ),
    ]
