# Generated by Django 3.2.6 on 2021-09-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0008_auto_20210916_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='resultados_de_aprendizaje',
            field=models.ManyToManyField(null=True, to='planificaciones.ResultadoDeAprendizaje'),
        ),
    ]
