# Generated by Django 2.2 on 2023-04-26 22:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0009_auto_20230417_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 26), null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fechaDeCreacion',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 26), null=True),
        ),
        migrations.AlterField(
            model_name='correccion',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creador_correccion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='correccion',
            name='fechaDeCreacion',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 26), null=True),
        ),
        migrations.AlterField(
            model_name='fundamentacion',
            name='fundamentos',
            field=models.CharField(max_length=4000),
        ),
    ]
