# Generated by Django 2.2 on 2023-04-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0010_auto_20230426_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundamentacion',
            name='fundamentos',
            field=models.TextField(),
        ),
    ]
