# Generated by Django 2.2 on 2021-08-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0011_auto_20210827_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('autores', models.CharField(max_length=50)),
                ('año_de_publicacion', models.CharField(max_length=50)),
                ('capitulos', models.CharField(max_length=50)),
                ('editores', models.CharField(max_length=50)),
                ('titulo_libro', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LibroWeb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('autores', models.CharField(max_length=50)),
                ('fecha_de_publicacion', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('nombre_pagina', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=60)),
            ],
        ),
    ]
