# Generated by Django 2.2 on 2023-05-19 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0012_auto_20230426_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 19), null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fechaDeCreacion',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 19), null=True),
        ),
        migrations.AlterField(
            model_name='correccion',
            name='fechaDeCreacion',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 19), null=True),
        ),
        migrations.AlterField(
            model_name='subcompetencia',
            name='descripcion',
            field=models.CharField(default='', max_length=300),
        ),
    ]
