# Generated by Django 2.2 on 2021-08-31 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0012_libro_libroweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='planificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion'),
        ),
        migrations.AddField(
            model_name='libroweb',
            name='planificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion'),
        ),
    ]
