# Generated by Django 3.2.6 on 2021-09-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0014_planificacion_justificacion_ordenanza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='justificacion_ordenanza',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
