# Generated by Django 3.2.6 on 2021-10-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0017_auto_20211002_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprofesorcatedra',
            name='actividades',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
