# Generated by Django 2.2 on 2021-09-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0018_auto_20210902_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprofesorcatedra',
            name='tareas',
            field=models.ManyToManyField(blank=True, to='planificaciones.TareasFunciones'),
        ),
    ]
