# Generated by Django 3.2.6 on 2021-10-12 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0023_rename_materialbibliografico_bibliografia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webgrafia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('titulo_publicacion', models.CharField(max_length=100)),
                ('nombre_pagina', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('link_pagina', models.CharField(max_length=100)),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('planificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.planificacion')),
            ],
        ),
    ]
