# Generated by Django 3.2.6 on 2021-11-08 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0018_resultadodeaprendizajeanterior_asignatura'),
        ('planificaciones', '0023_rename_materialbibliografico_bibliografia'),
    ]

    operations = [
    ]
