# Generated by Django 3.2.6 on 2021-11-08 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0024_merge_20211108_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstrategiasEns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=3)),
                ('estrategia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Webgrafia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('titulo_publicacion', models.CharField(max_length=100)),
                ('nombre_pagina', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('link_pagina', models.CharField(max_length=100)),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('planificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.planificacion')),
            ],
        ),
        migrations.CreateModel(
            name='PropuestaDesarrollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_dentro_aula', models.CharField(blank=True, max_length=3000, null=True)),
                ('actividad_fuera_aula', models.CharField(blank=True, max_length=3000, null=True)),
                ('tiempo_dentro_aula', models.CharField(blank=True, max_length=50, null=True)),
                ('tiempo_fuera_aula', models.CharField(blank=True, max_length=50, null=True)),
                ('modo_agrupamiento', models.CharField(blank=True, max_length=500, null=True)),
                ('materiales_equipamiento', models.CharField(blank=True, max_length=500, null=True)),
                ('unidades', models.IntegerField(blank=True, null=True)),
                ('bibliografias', models.ManyToManyField(blank=True, null=True, to='planificaciones.Bibliografia')),
                ('estrategias_ens', models.ManyToManyField(blank=True, null=True, to='planificaciones.EstrategiasEns')),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.planificacion')),
                ('resultados_de_aprendizaje', models.ManyToManyField(blank=True, null=True, to='planificaciones.ResultadoDeAprendizaje')),
                ('subcompetencias', models.ManyToManyField(blank=True, null=True, to='planificaciones.SubCompetencia')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivos', models.CharField(max_length=3000)),
                ('contenido', models.CharField(max_length=5000)),
                ('carga_horaria', models.CharField(max_length=100)),
                ('planificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.planificacion')),
                ('unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.unidad')),
            ],
        ),
    ]
