# Generated by Django 3.2.6 on 2021-10-14 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0024_contenido_webgrafia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_unidad', models.IntegerField()),
                ('titulo_unidad', models.CharField(max_length=100)),
                ('objetivos', models.CharField(max_length=3000)),
                ('contenido', models.CharField(max_length=5000)),
                ('carga_horaria', models.CharField(max_length=100)),
                ('planificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.planificacion')),
            ],
        ),
    ]
