# Generated by Django 2.2 on 2021-11-04 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0018_resultadodeaprendizajeanterior_asignatura'),
        ('planificaciones', '0025_contenido'),
    ]

    operations = [
    ]
