# Generated by Django 3.2.6 on 2021-11-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0025_contenido_estrategiasens_propuestadesarrollo_unidad_webgrafia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuestadesarrollo',
            name='unidades',
        ),
        migrations.AddField(
            model_name='propuestadesarrollo',
            name='unidades',
            field=models.ManyToManyField(blank=True, null=True, to='planificaciones.Unidad'),
        ),
    ]
