# Generated by Django 2.2 on 2021-11-04 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0026_merge_20211104_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_desarrollo_de_clase', models.CharField(blank=True, max_length=400, null=True)),
                ('fecha_clase', models.DateTimeField(auto_now=True, max_length=50)),
                ('numero_de_clase_o_semena', models.CharField(blank=True, max_length=400, null=True)),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion')),
                ('profesor_a_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Profesor')),
                ('resultado_de_aprendizaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.ResultadoDeAprendizaje')),
                ('unidad_tematica_o_tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Contenido')),
            ],
        ),
    ]
