# Generated by Django 3.2.6 on 2021-11-08 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0026_auto_20211108_0035'),
        ('planificaciones', '0028_auto_20211106_1856'),
    ]

    operations = [
    ]
