# Generated by Django 2.2 on 2021-11-14 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0029_merge_0026_auto_20211108_0035_0028_auto_20211106_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='subcompetencias',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(blank=True, default=datetime.date(2021, 11, 14), null=True),
        ),
    ]
