# Generated by Django 2.2 on 2021-12-15 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0030_auto_20211206_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechacalendarioacademico',
            name='editable',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 15), null=True),
        ),
        migrations.AlterField(
            model_name='fechacalendarioacademico',
            name='actividad',
            field=models.CharField(blank=True, choices=[('IC1', 'Inicio de clases 1er cuatrimestre'), ('FC1', 'Fin de clases 1er cuatrimestre'), ('IC2', 'Inicio de clases 2do cuatrimestre'), ('FC2', 'Fin de clases 2do cuatrimestre'), ('EF', 'Examen final con suspencion de clase'), ('EF', 'Examen final sin suspencion de clase'), ('RI', 'Receso de invierno'), ('F', 'Feriado'), ('DN', 'Dia Normal')], max_length=2, null=True),
        ),
    ]
