# Generated by Django 2.2 on 2021-12-21 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0033_fechacalendarioacademico_ciclo_lectivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacion',
            name='sincronizado_calendario_academico',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 21), null=True),
        ),
    ]
