# Generated by Django 3.2.6 on 2021-12-22 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0034_merge_20211221_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 21), null=True),
        ),
    ]
