# Generated by Django 2.2 on 2022-03-01 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0039_auto_20220226_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacion',
            name='estado',
            field=models.CharField(choices=[('P', 'En proceso'), ('A', 'Aprobada')], default='P', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 1), null=True),
        ),
    ]
