# Generated by Django 2.2 on 2023-01-21 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0049_auto_20230120_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='unidad_tematica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Unidad'),
        ),
    ]
