# Generated by Django 2.2 on 2021-08-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMateria', models.CharField(max_length=50)),
            ],
        ),
    ]
