# Generated by Django 2.2 on 2021-08-17 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCarrera', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('situacion', models.CharField(max_length=50)),
                ('dedicacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='carrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Carrera'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignatura',
            name='profesor',
            field=models.ManyToManyField(to='planificaciones.Profesor'),
        ),
    ]
