# Generated by Django 2.2 on 2021-09-07 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0002_remove_profesor_situacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_competencia', models.CharField(max_length=50)),
                ('competencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCompetencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad', models.CharField(max_length=50)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Competencia')),
            ],
        ),
    ]
