# Generated by Django 2.2 on 2021-09-02 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='dedicacion',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='situacion',
        ),
    ]
