# Generated by Django 2.2 on 2021-09-07 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0003_competencia_subcompetencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='planificacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion'),
            preserve_default=False,
        ),
    ]
