# Generated by Django 3.2.6 on 2021-09-18 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0003_actividad_resultadodeaprendizaje_tipodeevaluacion'),
        ('planificaciones', '0003_categoria_dedicacion_detalleprofesorcatedra_resultadodeaprendizaje_situacion_tareasfunciones'),
    ]

    operations = [
    ]
