# Generated by Django 2.2 on 2021-09-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0004_auto_20210917_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='eliminada',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
