# Generated by Django 2.2 on 2021-09-20 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0005_auto_20210918_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadodeaprendizaje',
            old_name='descripcion',
            new_name='resultado',
        ),
        migrations.AddField(
            model_name='resultadodeaprendizaje',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Asignatura'),
        ),
        migrations.AddField(
            model_name='resultadodeaprendizaje',
            name='planificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion'),
        ),
        migrations.AlterField(
            model_name='resultadodeaprendizaje',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ResultadoDeAprendizajes',
        ),
    ]
