# Generated by Django 2.2 on 2021-09-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0006_auto_20210920_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadodeaprendizaje',
            name='resultado',
            field=models.CharField(max_length=300),
        ),
    ]
