# Generated by Django 2.2 on 2021-08-22 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0006_auto_20210818_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='dedicacion',
        ),
    ]
