# Generated by Django 2.2 on 2021-08-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0007_auto_20210820_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion1',
            name='cicloLectivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seccion1',
            name='cursado',
            field=models.CharField(blank=True, choices=[('A', 'Anual'), ('1', '1er Cuatrimestre'), ('2', '2do Cuatrimestre')], default='A', max_length=1, null=True),
        ),
    ]
