# Generated by Django 2.2 on 2021-08-23 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0008_auto_20210822_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dedicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dedicacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Situacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('situacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TareasFunciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tareaFunciones', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Categoria')),
            ],
        ),
    ]
