# Generated by Django 2.2 on 2021-08-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0008_auto_20210826_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seccion3',
            old_name='Fundamentos',
            new_name='fundamentos',
        ),
    ]
