# Generated by Django 2.2 on 2021-09-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0008_merge_20210921_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencia',
            name='competencia',
        ),
        migrations.RemoveField(
            model_name='subcompetencia',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='subcompetencia',
            name='competencia',
        ),
        migrations.AddField(
            model_name='competencia',
            name='descripcion',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='competencia',
            name='subcompetencias',
            field=models.ManyToManyField(blank=True, to='planificaciones.SubCompetencia'),
        ),
        migrations.AddField(
            model_name='subcompetencia',
            name='descripcion',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competencia',
            name='tipo_competencia',
            field=models.CharField(choices=[('T', 'Tecnológicas'), ('E', 'Específicas'), ('S', 'Sociales, políticas y actitudinales')], max_length=50),
        ),
    ]
