# Generated by Django 2.2 on 2021-09-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0009_auto_20210921_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcompetencia',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
