# Generated by Django 2.2 on 2021-08-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0009_auto_20210827_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planificacion',
            old_name='Seccion3',
            new_name='seccion3',
        ),
    ]
