# Generated by Django 2.2 on 2021-08-24 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0009_categoria_dedicacion_situacion_tareasfunciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProfesorCatedra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Categoria')),
                ('dedicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Dedicacion')),
                ('situacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Situacion')),
                ('tareasFunciones', models.ManyToManyField(blank=True, null=True, to='planificaciones.TareasFunciones')),
            ],
        ),
    ]
