# Generated by Django 2.2 on 2021-09-21 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0010_auto_20210921_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencia',
            name='subcompetencias',
        ),
        migrations.DeleteModel(
            name='SubCompetencia',
        ),
    ]
