# Generated by Django 2.2 on 2021-08-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0010_detalleprofesorcatedra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='detalleprofesorcatedra',
            name='tareasFunciones',
        ),
        migrations.AddField(
            model_name='tareasfunciones',
            name='detalleprofesorcatedra',
            field=models.ManyToManyField(to='planificaciones.DetalleProfesorCatedra'),
        ),
    ]
