# Generated by Django 2.2 on 2021-08-24 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0011_auto_20210824_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprofesorcatedra',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Profesor'),
        ),
    ]
