# Generated by Django 3.2.6 on 2021-09-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0005_auto_20210917_2118'),
        ('planificaciones', '0012_subcompetencia'),
    ]

    operations = [
    ]
