# Generated by Django 2.2 on 2021-08-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0012_detalleprofesorcatedra_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='profesor',
            field=models.ManyToManyField(to='planificaciones.Profesor'),
        ),
    ]
