# Generated by Django 3.2.6 on 2021-09-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0013_merge_0005_auto_20210917_2118_0012_subcompetencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacion',
            name='justificacion_ordenanza',
            field=models.CharField(default='', max_length=3000),
            preserve_default=False,
        ),
    ]
