# Generated by Django 2.2 on 2021-08-24 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0013_asignatura_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprofesorcatedra',
            name='planificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion'),
        ),
    ]
