# Generated by Django 3.2.6 on 2021-09-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0015_alter_planificacion_justificacion_ordenanza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='condicion_aprobacion_cursada',
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='condicion_aprobacion_directa',
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
        migrations.DeleteModel(
            name='CondicionAprobacionCursada',
        ),
        migrations.DeleteModel(
            name='CondicionAprobacionDirecta',
        ),
    ]
