# Generated by Django 2.2 on 2021-08-31 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0011_auto_20210827_1636'),
        ('planificaciones', '0016_resultadodeaprendizaje'),
    ]

    operations = [
    ]
