# Generated by Django 2.2 on 2021-09-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0017_merge_20210831_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareasfunciones',
            name='detalle_profesor_catedra',
        ),
        migrations.AddField(
            model_name='detalleprofesorcatedra',
            name='tareas',
            field=models.ManyToManyField(blank=True, null=True, to='planificaciones.TareasFunciones'),
        ),
    ]
