# Generated by Django 3.2.6 on 2021-10-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0019_auto_20211011_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='material_bibliografico',
            field=models.ManyToManyField(blank=True, null=True, to='planificaciones.MaterialBibliografico'),
        ),
    ]
