# Generated by Django 3.2.6 on 2021-10-11 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0021_auto_20211011_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificacion',
            name='material_bibliografico',
        ),
        migrations.AddField(
            model_name='materialbibliografico',
            name='planificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.planificacion'),
        ),
    ]
