# Generated by Django 3.2.6 on 2021-10-11 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0022_auto_20211011_2102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialBibliografico',
            new_name='Bibliografia',
        ),
    ]
