# Generated by Django 2.2 on 2021-11-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0027_clase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='numero_de_clase_o_semena',
        ),
        migrations.AddField(
            model_name='clase',
            name='cantidad_tareas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='es_examen',
            field=models.CharField(blank=True, choices=[('P', 'Examen parcial'), ('R', 'Examen recuperatorio'), ('F', 'Examen final'), ('NA', 'No aplica')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='numero_de_clase_o_semana',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(auto_now=True, max_length=50),
        ),
        migrations.RemoveField(
            model_name='clase',
            name='profesor_a_cargo',
        ),
        migrations.AddField(
            model_name='clase',
            name='profesor_a_cargo',
            field=models.ManyToManyField(blank=True, to='planificaciones.Profesor'),
        ),
        migrations.RemoveField(
            model_name='clase',
            name='resultado_de_aprendizaje',
        ),
        migrations.AddField(
            model_name='clase',
            name='resultado_de_aprendizaje',
            field=models.ManyToManyField(blank=True, to='planificaciones.ResultadoDeAprendizaje'),
        ),
        migrations.RemoveField(
            model_name='clase',
            name='unidad_tematica_o_tema',
        ),
        migrations.AddField(
            model_name='clase',
            name='unidad_tematica_o_tema',
            field=models.ManyToManyField(blank=True, to='planificaciones.Contenido'),
        ),
    ]
