# Generated by Django 3.2.6 on 2021-12-01 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0029_merge_0026_auto_20211108_0035_0028_auto_20211106_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='año',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='comision',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 1), null=True),
        ),
    ]
