# Generated by Django 2.2 on 2021-12-06 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0029_merge_0026_auto_20211108_0035_0028_auto_20211106_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaCalendarioAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('nombre_mes', models.CharField(max_length=100, null=True)),
                ('nombre_dia', models.CharField(max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('hay_clase', models.BooleanField(null=True)),
                ('actividad', models.CharField(choices=[('F', 'Feriado'), ('EF', 'Examen Final'), ('RI', 'Receso Invernal'), ('IF', 'Inicio/Fin Clase'), ('DN', 'Dia Normal')], max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 6), null=True),
        ),
    ]
