# Generated by Django 3.2.6 on 2021-12-22 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0030_auto_20211201_1920'),
        ('planificaciones', '0033_fechacalendarioacademico_ciclo_lectivo'),
    ]

    operations = [
    ]
