# Generated by Django 3.2.6 on 2021-12-22 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0035_auto_20211221_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignatura',
            old_name='año',
            new_name='ano',
        ),
        migrations.AlterField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 22), null=True),
        ),
    ]
