# Generated by Django 2.2 on 2021-12-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0035_auto_20211222_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='profesor_a_cargo',
            field=models.ManyToManyField(blank=True, null=True, to='planificaciones.Profesor'),
        ),
    ]
