# Generated by Django 2.2 on 2022-02-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0036_auto_20211222_0947'),
        ('planificaciones', '0036_auto_20211222_1957'),
    ]

    operations = [
    ]
