# Generated by Django 2.2 on 2022-02-26 20:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0037_merge_20220226_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosdescriptivos',
            name='dias',
            field=models.CharField(blank=True, choices=[('L', 'Lunes'), ('M', 'Martes'), ('MI', 'Miercoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sabado')], default='L', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(blank=True, default=datetime.date(2022, 2, 26), null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='planificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Planificacion'),
        ),
    ]
