# Generated by Django 2.2 on 2022-02-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0038_auto_20220226_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasCursado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='datosdescriptivos',
            name='dias',
        ),
        migrations.AddField(
            model_name='datosdescriptivos',
            name='dias',
            field=models.ManyToManyField(blank=True, to='planificaciones.DiasCursado'),
        ),
    ]
