# Generated by Django 2.2 on 2023-01-05 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0040_auto_20220301_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(blank=True, default=datetime.date(2023, 1, 5), null=True),
        ),
    ]
