# Generated by Django 2.2 on 2023-01-06 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0042_comentario_correccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='correccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='planificaciones.Correccion'),
        ),
    ]
