# Generated by Django 2.2 on 2023-01-11 22:00

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0043_auto_20230105_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correccion',
            options={'ordering': ['estado']},
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='profesor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(blank=True, default=datetime.date(2023, 1, 11), null=True),
        ),
        migrations.AlterField(
            model_name='correccion',
            name='correccion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='estado',
            field=models.CharField(choices=[('P', 'En proceso'), ('A', 'Aprobada'), ('R', 'En revision'), ('C', 'A corregir')], max_length=2),
        ),
    ]
