# Generated by Django 2.2 on 2023-01-11 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0044_auto_20230111_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='profesor_a_cargo',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detalleprofesorcatedra',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
