# Generated by Django 2.2 on 2023-01-12 23:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planificaciones', '0045_auto_20230111_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(blank=True, default=datetime.date(2023, 1, 12), null=True),
        ),
        migrations.CreateModel(
            name='CarreraUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.Carrera')),
                ('usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
