# Generated by Django 2.2 on 2023-01-12 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planificaciones', '0046_auto_20230112_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrerausuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='carrerausuario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
