name: Django CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check Python version # checking the python version to see if 3.x is installed.
      run: python --version
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Check Syntax # check code formatting
      run: pycodestyle --statistics

