name: Django CI

on:
  push:
    branches: "develop"
env:
  AZURE_WEBAPP_NAME: Planacad # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'planacad/' # set this to the path to your web app project, defaults to the repository root


jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.16
    - name: Install Dependencies
      run: |
        pip install pip==9.0.1
        pip install -r planacad/requeriments.txt
    - name: Building web app
      uses: azure/appservice-build@v2
      with:
        source-dir: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
