name: Django CI

on:
  push:
    branches: "develop"
env:
  AZURE_WEBAPP_NAME: Planacad # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'planacad/' # set this to the path to your web app project, defaults to the repository root


jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v2
    - name: Building web app
      uses: azure/appservice-build@v1
      with:
          platform: python
          platform-version: 3.8
          source-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
